version: '3'
services:
  db:
    image: mysql
    expose:
      - "3306"
    environment:
      - MYSQL_USER=flask
      - MYSQL_ROOT_PASSWORD=flask
      - MYSQL_DATABASE=flask

  web:
    build: .
    ports:
     - "5000:5000"
    links:
     - db

